In [1]:
import torch
import math
from typing import List

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import nltk
import sentencepiece as spm
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [3]:
torch.cuda.get_device_name()

'NVIDIA GeForce GTX 1650 with Max-Q Design'

In [3]:
def pad_sents(sents, pad_token):
    """ Pad list of sentences according to the longest sentence in the batch.
        The paddings should be at the end of each sentence.
    @param sents (list[list[str]]): list of sentences, where each sentence
                                    is represented as a list of words
    @param pad_token (str): padding token
    @returns sents_padded (list[list[str]]): list of sentences where sentences shorter
        than the max length sentence are padded out with the pad_token, such that
        each sentences in the batch now has equal length.
    """
    sents_padded = []

    ### YOUR CODE HERE (~6 Lines)
    max_length = max([len(s) for s in sents])
    sents_padded = [sentence + [pad_token]*(max_length-len(sentence)) for sentence in sents]
    ### END YOUR CODE

    return sents_padded
sents = [['Hi','this','is','my','dog',".","His","name","is","Jone"],["hello",'I','am','John']]
pad_token = '<>'
pad_sents(sents, pad_token)

[['Hi', 'this', 'is', 'my', 'dog', '.', 'His', 'name', 'is', 'Jone'],
 ['hello', 'I', 'am', 'John', '<>', '<>', '<>', '<>', '<>', '<>']]

In [13]:
embedding = nn.Embedding(10, 3, padding_idx=2)
embedding.weight

Parameter containing:
tensor([[ 0.7831,  0.1088, -0.4200],
        [-0.7239,  0.9402,  0.2234],
        [ 0.0000,  0.0000,  0.0000],
        [-0.8828,  0.9722, -0.2331],
        [ 0.0344, -1.2378, -0.2923],
        [ 1.1123, -0.4968, -0.2691],
        [ 0.4424,  0.9856, -0.3367],
        [ 0.3591,  0.1401, -0.5762],
        [-1.7043, -0.4807, -1.4128],
        [ 0.2419,  0.4790,  0.0478]], requires_grad=True)

In [16]:
input = torch.LongTensor([[3,1,4,5,6,2]])
embedding(input)

tensor([[[-0.8828,  0.9722, -0.2331],
         [-0.7239,  0.9402,  0.2234],
         [ 0.0344, -1.2378, -0.2923],
         [ 1.1123, -0.4968, -0.2691],
         [ 0.4424,  0.9856, -0.3367],
         [ 0.0000,  0.0000,  0.0000]]], grad_fn=<EmbeddingBackward0>)

In [29]:
m= nn.Dropout(p=0.2)
input = torch.randn(2, 3)
output = m(input)

In [30]:
input

tensor([[ 0.5696, -1.6651,  2.1375],
        [-0.0653, -1.5919, -1.0968]])

In [31]:
output

tensor([[ 0.7120, -0.0000,  2.6718],
        [-0.0816, -1.9899, -1.3710]])

In [34]:
input = torch.randn(2, 3)
m = nn.Linear(3, 2)
output = m(input)

In [36]:
input

tensor([[-0.1235, -1.0468,  0.2595],
        [ 0.0243, -1.9398, -0.0212]])

In [37]:
output

tensor([[-0.1749, -0.4994],
        [-0.1314, -0.6735]], grad_fn=<AddmmBackward0>)

In [1]:
import math
import sys
import pickle
import time


from docopt import docopt
# from nltk.translate.bleu_score import corpus_bleu, sentence_bleu, SmoothingFunction
import sacrebleu
from nmt_model import Hypothesis, NMT
import numpy as np
from typing import List, Tuple, Dict, Set, Union
from tqdm import tqdm
from utils import read_corpus, batch_iter
from vocab import Vocab, VocabEntry

import torch
import torch.nn.utils
from torch.utils.tensorboard import SummaryWriter

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\USER\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [4]:
args = docopt(__doc__)
train_data_src = read_corpus(args['--train-src'], source='src', vocab_size=21000)       # EDIT: NEW VOCAB SIZE
train_data_tgt = read_corpus(args['--train-tgt'], source='tgt', vocab_size=8000)

TypeError: docopt() missing 1 required positional argument: 'doc'