In [31]:
from word2vec import *
from utils.utils import *

In [32]:
sigmoid(0.5)

0.6224593312018546

In [33]:
import numpy as np

# Create two matrices
outsideVectors = np.array([[1, 2], [3, 4]])
centerWordVec = np.array([5, 6])

# Multiply the two matrices together using the @ operator
y_hat = outsideVectors @ centerWordVec

# Print the output vector
print(y_hat)

[17 39]


In [34]:
np.zeros_like(y_hat)

array([0, 0])

In [35]:
print(softmax(y_hat))
np.exp(17)/(np.exp(17)+np.exp(39))

[2.78946809e-10 1.00000000e+00]


2.7894680920908113e-10

In [36]:
outsideVectors = np.array([[1,2,3,1],[4,2,1,3],[5,8,9,2]])
centerWordVec = np.array([2,3,1,4])
print(outsideVectors @ centerWordVec)
softmax(outsideVectors @ centerWordVec)

[15 27 51]


array([2.31952283e-16, 3.77513454e-11, 1.00000000e+00])

In [29]:
np.dot(centerWordVec.reshape([1, -1]), outsideVectors.T)

array([[15, 27, 51]])

In [37]:
np.outer([1,2,3],[3,2,1])

array([[3, 2, 1],
       [6, 4, 2],
       [9, 6, 3]])